projection ::= Expression

Expression ::= LogicalOperator | Condition
LogicalOperator ::= Expression ('&' | '|') Expression
Condition ::= IntCondition | StringCondition | faultTypeCondition
IntCondition ::= IntAttribute Test Int
IntAttribute ::= 'inputLabel' | 'inputIndex' | 'channelIndex' | 'bitIndex'
StringCondition ::= 'layerId' Test String
faultTypeCondition ::= 'faultType' Test ('STUCK_AT_0' | 'STUCK_AT_1' | 'BITFLIP' | 'NONE')

range ::= Int ("until" | "to") Int
Int ::= "-"? (digit)+
Float ::= Int "." (digit)+
String ::= "'" alphaNumChar+ "'"
Test ::= ('!=' | '==')
alphaNumChar ::= alphaChar | digit
alphaChar ::= "a"| "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" |
"A"| "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
digit ::= "0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"
